services:
  iam-service:
    image: ghcr.io/settlehub/iam-service:latest
    container_name: iam-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      
      - IAM_DB_URL=${IAM_DB_URL:-jdbc:postgresql://localhost:5432/iam-service-db}
      - IAM_DB_USERNAME=${IAM_DB_USERNAME}
      - IAM_DB_PASSWORD=${IAM_DB_PASSWORD}
      
      - KAFKA_ADDRESS=${KAFKA_ADDRESS}
      
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

      - EUREKA_ADDRESS=${EUREKA_ADDRESS}

      - IAM_SERVICE_IP=${IAM_SERVICE_IP}
      
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m 

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
