name: CD Pipeline (Deploy to Server)

on:
  workflow_run:
    workflows: ["CD Pipeline (Publish Image)"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: self-hosted
    
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy compose.yml to Target Machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "compose.yml"
          target: "/opt/settlehub/iam/"

      - name: Deploy to Target Machine via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IAM_DB_URL: ${{ secrets.IAM_DB_URL }}
          IAM_DB_USERNAME: ${{ secrets.IAM_DB_USERNAME }}
          IAM_DB_PASSWORD: ${{ secrets.IAM_DB_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          KAFKA_ADDRESS: ${{ secrets.KAFKA_ADDRESS }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          envs: IAM_DB_URL,IAM_DB_USERNAME,IAM_DB_PASSWORD,JWT_SECRET_KEY,KAFKA_ADDRESS,IMAGE_TAG
          script: |
            cd /opt/settlehub/iam/
            
            echo "IAM_DB_URL=$IAM_DB_URL" > .env
            echo "IAM_DB_USERNAME=$IAM_DB_USERNAME" >> .env
            echo "IAM_DB_PASSWORD=$IAM_DB_PASSWORD" >> .env
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
            echo "KAFKA_ADDRESS=$KAFKA_ADDRESS" >> .env
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker pull ghcr.io/settlehub/iam-service:$IMAGE_TAG
            
            docker compose up -d
            
            docker image prune -a -f --filter "until=24h"